### ISSUE TITLE
Looking to integrate rewrite recipe with https://github.com/NerdWalletOSS/shepherd

### ISSUE THREAD

**Issue by kavitha186** [openrewrite/rewrite-feature-flags#37]
Hi @timtebeek I'm the maintainer for https://github.com/NerdWalletOSS/shepherd and looking to integrate rewrite recipes with shepherd. Please let me know your thoughts

**Comment by timtebeek** [comment]
hi @kavitha186 ; perhaps I'm missing something, but there's no direct link with the rewrite-feature-flags project right?

You might be interested to look at https://app.moderne.io/marketplace, which is how we automate running recipes at scale.
That also uniquely leverages running recipes from serialized LSTs for a considerable speedup. I hope that's of interest to you.
This video goes into[ the differences between OpenRewrite and Moderne](https://www.youtube.com/watch?v=Q-ej2lCJHRs).

Since there's no direct link with the particular recipe module I'll close this issue already. We can discuss more via other channels like Discord or Slack if you're interested. And thanks again for your help improving the recipes here.

**Comment by kavitha186** [comment]
Yes I agree it is not related to this particular recipe. But yes Shepherd does the same as moderne cli does .
